// <auto-generated />
using Mango.Services.ProductAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230315054014_create-database")]
    partial class createdatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Mango.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Appetizer",
                            Description = "Bengali food",
                            ImageUrl = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Frecipes.timesofindia.com%2Fphoto%2F61050397.cms%3Fimgsize%3D347173&f=1&nofb=1&ipt=3cdd2ac8943bddd345218b343980f594ba8659340471dfa65442c28a21d46246&ipo=images",
                            Name = "Samosa",
                            Price = 15.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Non-veg",
                            Description = "Bengali food",
                            ImageUrl = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.ytimg.com%2Fvi%2F88ZnKxw8E-s%2Fmaxresdefault.jpg&f=1&nofb=1&ipt=e6912acfb5e5be74c17550bb88a4d411faeac06912c3e81bceaa1ca494103a72&ipo=images",
                            Name = "Chicken Kosa",
                            Price = 85.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Dessert",
                            Description = "Bengali favourite sweet",
                            ImageUrl = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcdn.tasteatlas.com%2FImages%2FDishes%2F65905512a4d9433780979b91393530b0.jpg%3Fmw%3D1300&f=1&nofb=1&ipt=981b7c0eaee775bfd4a8f914ac0e460608fea433077762d90e21543e5a07961b&ipo=images",
                            Name = "Sweet Pie",
                            Price = 10.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
